# Generated by Django 3.0.3 on 2020-03-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200229_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='feet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='inches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1000),
        ),
    ]
